[theme]

# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
# base = 'light'

# Primary accent for interactive elements
# primaryColor = ''

# Background color for the main content area
# backgroundColor = ''

# Background color for sidebar and most interactive widgets
# secondaryBackgroundColor = ''

# Color used for almost all text
# textColor = ''

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"